[providers]
php = "74"

[phases.setup]
nixPkgs = ["php74", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

